application:
  subdomain: songloft
  multi_instance: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://songloft-app:58091/
  injects:
    - id: login-autofill
      when:
        - /#/login
      do:
        - src: builtin://simple-inject-password
          params:
            user: "{{ .U.admin_username }}"
            password: "{{ .U.admin_password }}"
services:
  songloft-app:
    # songloft/songloft:2.9.6
    # upstream: songloft/songloft:2.11.4
    image: songloft/songloft:2.11.4
    environment:
      - ADMIN_USERNAME={{.U.admin_username}}
      - ADMIN_PASSWORD={{.U.admin_password}}
    binds:
      - /lzcapp/run/mnt/home/{{.U.music_dir_name}}:/app/music
      - /lzcapp/var/data:/app/data
    cpu_shares: 512
    mem_limit: 512M
ext_config:
  enable_media_access: true
  enable_document_access: true
  permissions:
    - PERM_MEDIA_MOUNT_SHARED
