package: community.lazycat.app.songloft
version: 2.11.0
name: Songloft
description: "个人音乐服务器"
min_os_version: 1.5.0
license: Apache-2.0 license
homepage: https://github.com/songloft-org/songloft
author: songloft-org
locales:
  en:
    name: "Songloft"
    description: "A music streaming server for your personal music collection"
  zh:
    name: "Songloft"
    description: "自托管个人音乐服务器"
permissions:
  required:
    - net.internet
    - document.read
  optional:
    - document.write
    - device.dri.render
    - power.shutdown.inhibit
